### ISSUE TITLE
CAN-BUS Connection

### ISSUE THREAD

**Issue by julesguy** [bwurst/hargassner-monitor#2]
Hallo, ich suche nach Informationen, wie ich mein CAN-BUS-Modul an den Hargassner-Kessel anschließen kann.
Es tut mir leid, ein Problem zu erstellen. Nur so kann ich Sie kontaktieren.
Wo haben Sie sich mit dem CAN-Bus verbunden? Ich habe die L- und H-Verbindungen gefunden, aber sie scheinen keine Stromversorgung zu haben. Vielen Dank, dass Sie Ihre Erfahrungen in Ihrem Blog und Code geteilt haben! (Wenn die Übersetzung nicht gut ist, ist es Googles Schuld, ich bin Franzose!).

**Comment by bwurst** [comment]
Ich habe eine CAN-Bus-Verbindung vom Kessel zu den Haus-Steuerungen (wir nutzen den Heizkreisregler im Kessel gar nicht sondern zusätzliche Haus-Steuerungen). An dieser Verbindung hatte ich angeschlossen. Da mein CAN-Bus-Modul aber von schlechter Qualität war und ab und zu die Verbindung gestört hat, benutze ich es jetzt nicht mehr. Ich überwache die Heizung nur noch über serielle Verbindung.

Bei mir ist die CAN-Bus-Leitung bei H (gelb) und L (grün) angeschlossen. Eventuell muss das noch über einen Schalter aktiviert werden, das hat bei mir der Installateur gemacht.

**Comment by bwurst** [comment]
Teilweise. Ich habe z.B. aus der CAN-Verbindung die Daten zur "Anforderung" der Heizkreisregler extrahiert, da ich diese im RS232 nicht gefunden habe. 
In canbus/bin/canmonitor.py ist der Code, der die entsprechenden IDs verarbeitet.

**Comment by EverestOS** [comment]
Ja genau. 
Aber der Code wertet nicht aus, was 0x161 oder 0x14d steht? 

Beispiel von meiner Anlage (es gibt zwei HKR) 
";"14E";"8";"05 6A 01 00 00 16 01 01";".j......"
";"162";"8";"40 04 15 AD 15 AD 15 AD";"@......."
";"14D";"8";"01 00 64 00 09 0A 0B 00";"..d....."
 ";"161";"8";"09 AB 15 8F 15 91 15 8F";"........"
 ";"14E";"8";"06 14 64 00 00 00 00 00";"..d....."
 ";"162";"8";"70 00 00 00 00 00 00 00";"p......."
 ";"14D";"8";"06 00 64 00 00 00 00 00";"..d....."

**Comment by bwurst** [comment]
Im Code sind diese IDs erwähnt aber ich denke, ich habe einfach nicht herausgefunden welche Daten da drin stecken.
In Zeile 81ff konnte ich immerhin zuordnen, dass diese beiden IDs für HKR1 sind. Aber ansonsten werden die Daten dort einfach ins Logfile geschrieben.
https://github.com/bwurst/hargassner-monitor/blob/4f64bb46d3e057057a71542e564ab7c0e0cd0608/canbus/bin/canmonitor.py#L81
